"""Module for working with Y92 codes"""


def get_mapping() -> dict:
    """Returns the Y92 mapping"""

    mapping = {
        "Y92.0": "Non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.00": "Unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.000": "Kitchen of unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.001": "Dining room of unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.002": "Bathroom of unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.003": "Bedroom of unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.007": "Garden or yard of unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.008": "Other place in unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.009": "Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause",
        "Y92.01": "Single-family non-institutional (private) house as the place of occurrence of the external cause",
        "Y92.010": "Kitchen of single-family (private) house as the place of occurrence of the external cause",
        "Y92.011": "Dining room of single-family (private) house as the place of occurrence of the external cause",
        "Y92.012": "Bathroom of single-family (private) house as the place of occurrence of the external cause",
        "Y92.013": "Bedroom of single-family (private) house as the place of occurrence of the external cause",
        "Y92.014": "Private driveway to single-family (private) house as the place of occurrence of the external cause",
        "Y92.015": "Private garage of single-family (private) house as the place of occurrence of the external cause",
        "Y92.016": "Swimming-pool in single-family (private) house or garden as the place of occurrence of the external cause",
        "Y92.017": "Garden or yard in single-family (private) house as the place of occurrence of the external cause",
        "Y92.018": "Other place in single-family (private) house as the place of occurrence of the external cause",
        "Y92.019": "Unspecified place in single-family (private) house as the place of occurrence of the external cause",
        "Y92.02": "Mobile home as the place of occurrence of the external cause",
        "Y92.020": "Kitchen in mobile home as the place of occurrence of the external cause",
        "Y92.021": "Dining room in mobile home as the place of occurrence of the external cause",
        "Y92.022": "Bathroom in mobile home as the place of occurrence of the external cause",
        "Y92.023": "Bedroom in mobile home as the place of occurrence of the external cause",
        "Y92.024": "Driveway of mobile home as the place of occurrence of the external cause",
        "Y92.025": "Garage of mobile home as the place of occurrence of the external cause",
        "Y92.026": "Swimming-pool of mobile home as the place of occurrence of the external cause",
        "Y92.027": "Garden or yard of mobile home as the place of occurrence of the external cause",
        "Y92.028": "Other place in mobile home as the place of occurrence of the external cause",
        "Y92.029": "Unspecified place in mobile home as the place of occurrence of the external cause",
        "Y92.03": "Apartment as the place of occurrence of the external cause",
        "Y92.030": "Kitchen in apartment as the place of occurrence of the external cause",
        "Y92.031": "Bathroom in apartment as the place of occurrence of the external cause",
        "Y92.032": "Bedroom in apartment as the place of occurrence of the external cause",
        "Y92.038": "Other place in apartment as the place of occurrence of the external cause",
        "Y92.039": "Unspecified place in apartment as the place of occurrence of the external cause",
        "Y92.04": "Boarding-house as the place of occurrence of the external cause",
        "Y92.040": "Kitchen in boarding-house as the place of occurrence of the external cause",
        "Y92.041": "Bathroom in boarding-house as the place of occurrence of the external cause",
        "Y92.042": "Bedroom in boarding-house as the place of occurrence of the external cause",
        "Y92.043": "Driveway of boarding-house as the place of occurrence of the external cause",
        "Y92.044": "Garage of boarding-house as the place of occurrence of the external cause",
        "Y92.045": "Swimming-pool of boarding-house as the place of occurrence of the external cause",
        "Y92.046": "Garden or yard of boarding-house as the place of occurrence of the external cause",
        "Y92.048": "Other place in boarding-house as the place of occurrence of the external cause",
        "Y92.049": "Unspecified place in boarding-house as the place of occurrence of the external cause",
        "Y92.09": "Other non-institutional residence as the place of occurrence of the external cause",
        "Y92.090": "Kitchen in other non-institutional residence as the place of occurrence of the external cause",
        "Y92.091": "Bathroom in other non-institutional residence as the place of occurrence of the external cause",
        "Y92.092": "Bedroom in other non-institutional residence as the place of occurrence of the external cause",
        "Y92.093": "Driveway of other non-institutional residence as the place of occurrence of the external cause",
        "Y92.094": "Garage of other non-institutional residence as the place of occurrence of the external cause",
        "Y92.095": "Swimming-pool of other non-institutional residence as the place of occurrence of the external cause",
        "Y92.096": "Garden or yard of other non-institutional residence as the place of occurrence of the external cause",
        "Y92.098": "Other place in other non-institutional residence as the place of occurrence of the external cause",
        "Y92.099": "Unspecified place in other non-institutional residence as the place of occurrence of the external cause",
        "Y92.1": "Institutional (nonprivate) residence as the place of occurrence of the external cause",
        "Y92.10": "Unspecified residential institution as the place of occurrence of the external cause",
        "Y92.11": "Children's home and orphanage as the place of occurrence of the external cause",
        "Y92.110": "Kitchen in children's home and orphanage as the place of occurrence of the external cause",
        "Y92.111": "Bathroom in children's home and orphanage as the place of occurrence of the external cause",
        "Y92.112": "Bedroom in children's home and orphanage as the place of occurrence of the external cause",
        "Y92.113": "Driveway of children's home and orphanage as the place of occurrence of the external cause",
        "Y92.114": "Garage of children's home and orphanage as the place of occurrence of the external cause",
        "Y92.115": "Swimming-pool of children's home and orphanage as the place of occurrence of the external cause",
        "Y92.116": "Garden or yard of children's home and orphanage as the place of occurrence of the external cause",
        "Y92.118": "Other place in children's home and orphanage as the place of occurrence of the external cause",
        "Y92.119": "Unspecified place in children's home and orphanage as the place of occurrence of the external cause",
        "Y92.12": "Nursing home as the place of occurrence of the external cause",
        "Y92.120": "Kitchen in nursing home as the place of occurrence of the external cause",
        "Y92.121": "Bathroom in nursing home as the place of occurrence of the external cause",
        "Y92.122": "Bedroom in nursing home as the place of occurrence of the external cause",
        "Y92.123": "Driveway of nursing home as the place of occurrence of the external cause",
        "Y92.124": "Garage of nursing home as the place of occurrence of the external cause",
        "Y92.125": "Swimming-pool of nursing home as the place of occurrence of the external cause",
        "Y92.126": "Garden or yard of nursing home as the place of occurrence of the external cause",
        "Y92.128": "Other place in nursing home as the place of occurrence of the external cause",
        "Y92.129": "Unspecified place in nursing home as the place of occurrence of the external cause",
        "Y92.13": "Military base as the place of occurrence of the external cause",
        "Y92.130": "Kitchen on military base as the place of occurrence of the external cause",
        "Y92.131": "Mess hall on military base as the place of occurrence of the external cause",
        "Y92.133": "Barracks on military base as the place of occurrence of the external cause",
        "Y92.135": "Garage on military base as the place of occurrence of the external cause",
        "Y92.136": "Swimming-pool on military base as the place of occurrence of the external cause",
        "Y92.137": "Garden or yard on military base as the place of occurrence of the external cause",
        "Y92.138": "Other place on military base as the place of occurrence of the external cause",
        "Y92.139": "Unspecified place military base as the place of occurrence of the external cause",
        "Y92.14": "Prison as the place of occurrence of the external cause",
        "Y92.140": "Kitchen in prison as the place of occurrence of the external cause",
        "Y92.141": "Dining room in prison as the place of occurrence of the external cause",
        "Y92.142": "Bathroom in prison as the place of occurrence of the external cause",
        "Y92.143": "Cell of prison as the place of occurrence of the external cause",
        "Y92.146": "Swimming-pool of prison as the place of occurrence of the external cause",
        "Y92.147": "Courtyard of prison as the place of occurrence of the external cause",
        "Y92.148": "Other place in prison as the place of occurrence of the external cause",
        "Y92.149": "Unspecified place in prison as the place of occurrence of the external cause",
        "Y92.15": "Reform school as the place of occurrence of the external cause",
        "Y92.150": "Kitchen in reform school as the place of occurrence of the external cause",
        "Y92.151": "Dining room in reform school as the place of occurrence of the external cause",
        "Y92.152": "Bathroom in reform school as the place of occurrence of the external cause",
        "Y92.153": "Bedroom in reform school as the place of occurrence of the external cause",
        "Y92.154": "Driveway of reform school as the place of occurrence of the external cause",
        "Y92.155": "Garage of reform school as the place of occurrence of the external cause",
        "Y92.156": "Swimming-pool of reform school as the place of occurrence of the external cause",
        "Y92.157": "Garden or yard of reform school as the place of occurrence of the external cause",
        "Y92.158": "Other place in reform school as the place of occurrence of the external cause",
        "Y92.159": "Unspecified place in reform school as the place of occurrence of the external cause",
        "Y92.16": "School dormitory as the place of occurrence of the external cause",
        "Y92.160": "Kitchen in school dormitory as the place of occurrence of the external cause",
        "Y92.161": "Dining room in school dormitory as the place of occurrence of the external cause",
        "Y92.162": "Bathroom in school dormitory as the place of occurrence of the external cause",
        "Y92.163": "Bedroom in school dormitory as the place of occurrence of the external cause",
        "Y92.168": "Other place in school dormitory as the place of occurrence of the external cause",
        "Y92.169": "Unspecified place in school dormitory as the place of occurrence of the external cause",
        "Y92.19": "Other specified residential institution as the place of occurrence of the external cause",
        "Y92.190": "Kitchen in other specified residential institution as the place of occurrence of the external cause",
        "Y92.191": "Dining room in other specified residential institution as the place of occurrence of the external cause",
        "Y92.192": "Bathroom in other specified residential institution as the place of occurrence of the external cause",
        "Y92.193": "Bedroom in other specified residential institution as the place of occurrence of the external cause",
        "Y92.194": "Driveway of other specified residential institution as the place of occurrence of the external cause",
        "Y92.195": "Garage of other specified residential institution as the place of occurrence of the external cause",
        "Y92.196": "Pool of other specified residential institution as the place of occurrence of the external cause",
        "Y92.197": "Garden or yard of other specified residential institution as the place of occurrence of the external cause",
        "Y92.198": "Other place in other specified residential institution as the place of occurrence of the external cause",
        "Y92.199": "Unspecified place in other specified residential institution as the place of occurrence of the external cause",
        "Y92.2": "School, other institution and public administrative area as the place of occurrence of the external cause",
        "Y92.21": "School (private) (public) (state) as the place of occurrence of the external cause",
        "Y92.210": "Daycare center as the place of occurrence of the external cause",
        "Y92.211": "Elementary school as the place of occurrence of the external cause",
        "Y92.212": "Middle school as the place of occurrence of the external cause",
        "Y92.213": "High school as the place of occurrence of the external cause",
        "Y92.214": "College as the place of occurrence of the external cause",
        "Y92.215": "Trade school as the place of occurrence of the external cause",
        "Y92.218": "Other school as the place of occurrence of the external cause",
        "Y92.219": "Unspecified school as the place of occurrence of the external cause",
        "Y92.22": "Religious institution as the place of occurrence of the external cause",
        "Y92.23": "Hospital as the place of occurrence of the external cause",
        "Y92.230": "Patient room in hospital as the place of occurrence of the external cause",
        "Y92.231": "Patient bathroom in hospital as the place of occurrence of the external cause",
        "Y92.232": "Corridor of hospital as the place of occurrence of the external cause",
        "Y92.233": "Cafeteria of hospital as the place of occurrence of the external cause",
        "Y92.234": "Operating room of hospital as the place of occurrence of the external cause",
        "Y92.238": "Other place in hospital as the place of occurrence of the external cause",
        "Y92.239": "Unspecified place in hospital as the place of occurrence of the external cause",
        "Y92.24": "Public administrative building as the place of occurrence of the external cause",
        "Y92.240": "Courthouse as the place of occurrence of the external cause",
        "Y92.241": "Library as the place of occurrence of the external cause",
        "Y92.242": "Post office as the place of occurrence of the external cause",
        "Y92.243": "City hall as the place of occurrence of the external cause",
        "Y92.248": "Other public administrative building as the place of occurrence of the external cause",
        "Y92.25": "Cultural building as the place of occurrence of the external cause",
        "Y92.250": "Art Gallery as the place of occurrence of the external cause",
        "Y92.251": "Museum as the place of occurrence of the external cause",
        "Y92.252": "Music hall as the place of occurrence of the external cause",
        "Y92.253": "Opera house as the place of occurrence of the external cause",
        "Y92.254": "Theater (live) as the place of occurrence of the external cause",
        "Y92.258": "Other cultural public building as the place of occurrence of the external cause",
        "Y92.26": "Movie house or cinema as the place of occurrence of the external cause",
        "Y92.29": "Other specified public building as the place of occurrence of the external cause",
        "Y92.3": "Sports and athletics area as the place of occurrence of the external cause",
        "Y92.31": "Athletic court as the place of occurrence of the external cause",
        "Y92.310": "Basketball court as the place of occurrence of the external cause",
        "Y92.311": "Squash court as the place of occurrence of the external cause",
        "Y92.312": "Tennis court as the place of occurrence of the external cause",
        "Y92.318": "Other athletic court as the place of occurrence of the external cause",
        "Y92.32": "Athletic field as the place of occurrence of the external cause",
        "Y92.320": "Baseball field as the place of occurrence of the external cause",
        "Y92.321": "Football field as the place of occurrence of the external cause",
        "Y92.322": "Soccer field as the place of occurrence of the external cause",
        "Y92.328": "Other athletic field as the place of occurrence of the external cause",
        "Y92.33": "Skating rink as the place of occurrence of the external cause",
        "Y92.330": "Ice skating rink (indoor) (outdoor) as the place of occurrence of the external cause",
        "Y92.331": "Roller skating rink as the place of occurrence of the external cause",
        "Y92.34": "Swimming pool (public) as the place of occurrence of the external cause",
        "Y92.39": "Other specified sports and athletic area as the place of occurrence of the external cause",
        "Y92.4": "Street, highway and other paved roadways as the place of occurrence of the external cause",
        "Y92.41": "Street and highway as the place of occurrence of the external cause",
        "Y92.410": "Unspecified street and highway as the place of occurrence of the external cause",
        "Y92.411": "Interstate highway as the place of occurrence of the external cause",
        "Y92.412": "Parkway as the place of occurrence of the external cause",
        "Y92.413": "State road as the place of occurrence of the external cause",
        "Y92.414": "Local residential or business street as the place of occurrence of the external cause",
        "Y92.415": "Exit ramp or entrance ramp of street or highway as the place of occurrence of the external cause",
        "Y92.48": "Other paved roadways as the place of occurrence of the external cause",
        "Y92.480": "Sidewalk as the place of occurrence of the external cause",
        "Y92.481": "Parking lot as the place of occurrence of the external cause",
        "Y92.482": "Bike path as the place of occurrence of the external cause",
        "Y92.488": "Other paved roadways as the place of occurrence of the external cause",
        "Y92.5": "Trade and service area as the place of occurrence of the external cause",
        "Y92.51": "Private commercial establishments as the place of occurrence of the external cause",
        "Y92.510": "Bank as the place of occurrence of the external cause",
        "Y92.511": "Restaurant or cafe as the place of occurrence of the external cause",
        "Y92.512": "Supermarket, store or market as the place of occurrence of the external cause",
        "Y92.513": "Shop (commercial) as the place of occurrence of the external cause",
        "Y92.52": "Service areas as the place of occurrence of the external cause",
        "Y92.520": "Airport as the place of occurrence of the external cause",
        "Y92.521": "Bus station as the place of occurrence of the external cause",
        "Y92.522": "Railway station as the place of occurrence of the external cause",
        "Y92.523": "Highway rest stop as the place of occurrence of the external cause",
        "Y92.524": "Gas station as the place of occurrence of the external cause",
        "Y92.53": "Ambulatory health services establishments as the place of occurrence of the external cause",
        "Y92.530": "Ambulatory surgery center as the place of occurrence of the external cause",
        "Y92.531": "Health care provider office as the place of occurrence of the external cause",
        "Y92.532": "Urgent care center as the place of occurrence of the external cause",
        "Y92.538": "Other ambulatory health services establishments as the place of occurrence of the external cause",
        "Y92.59": "Other trade areas as the place of occurrence of the external cause",
        "Y92.6": "Industrial and construction area as the place of occurrence of the external cause",
        "Y92.61": "Building [any] under construction as the place of occurrence of the external cause",
        "Y92.62": "Dock or shipyard as the place of occurrence of the external cause",
        "Y92.63": "Factory as the place of occurrence of the external cause",
        "Y92.64": "Mine or pit as the place of occurrence of the external cause",
        "Y92.65": "Oil rig as the place of occurrence of the external cause",
        "Y92.69": "Other specified industrial and construction area as the place of occurrence of the external cause",
        "Y92.7": "Farm as the place of occurrence of the external cause",
        "Y92.71": "Barn as the place of occurrence of the external cause",
        "Y92.72": "Chicken coop as the place of occurrence of the external cause",
        "Y92.73": "Farm field as the place of occurrence of the external cause",
        "Y92.74": "Orchard as the place of occurrence of the external cause",
        "Y92.79": "Other farm location as the place of occurrence of the external cause",
        "Y92.8": "Other places as the place of occurrence of the external cause",
        "Y92.81": "Transport vehicle as the place of occurrence of the external cause",
        "Y92.810": "Car as the place of occurrence of the external cause",
        "Y92.811": "Bus as the place of occurrence of the external cause",
        "Y92.812": "Truck as the place of occurrence of the external cause",
        "Y92.813": "Airplane as the place of occurrence of the external cause",
        "Y92.814": "Boat as the place of occurrence of the external cause",
        "Y92.815": "Train as the place of occurrence of the external cause",
        "Y92.816": "Subway car as the place of occurrence of the external cause",
        "Y92.818": "Other transport vehicle as the place of occurrence of the external cause",
        "Y92.82": "Wilderness area",
        "Y92.820": "Desert as the place of occurrence of the external cause",
        "Y92.821": "Forest as the place of occurrence of the external cause",
        "Y92.828": "Other wilderness area as the place of occurrence of the external cause",
        "Y92.83": "Recreation area as the place of occurrence of the external cause",
        "Y92.830": "Public park as the place of occurrence of the external cause",
        "Y92.831": "Amusement park as the place of occurrence of the external cause",
        "Y92.832": "Beach as the place of occurrence of the external cause",
        "Y92.833": "Campsite as the place of occurrence of the external cause",
        "Y92.834": "Zoological garden (Zoo) as the place of occurrence of the external cause",
        "Y92.838": "Other recreation area as the place of occurrence of the external cause",
        "Y92.84": "Military training ground as the place of occurrence of the external cause",
        "Y92.85": "Railroad track as the place of occurrence of the external cause",
        "Y92.86": "Slaughter house as the place of occurrence of the external cause",
        "Y92.89": "Other specified places as the place of occurrence of the external cause",
        "Y92.9": "Unspecified place or not applicable",
    }

    return mapping

def to_description(code, default=None):
    """Returns the description for the provided code
    Raises a KeyError exception if the code does not match the data dictionary for Y92 code listing
    """

    if code == "7701001":
        return "Not Applicable"
    elif code == "7701003":
        return "Not Recorded"

    try:
        description = get_mapping()[code]
    # except KeyError as error:
    #     raise error.add_note(f"""{code} is an invalid code. It is not in the NEMSIS data dictionary
    #                      or Y92 code listings""")
    except KeyError as error:
        if default is None:
            raise KeyError(
                f"{code} is an invalid code. Not in the NEMSIS data dictionary or Y92 code listings."
            ) from error
        return "not-found"

    return description
